#!/bin/bash
# wget the file
# chmod 755 sudoin
# ./sudoin
wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add - 
sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
sudo apt-get  --yes --force-yesupdate 
sudo apt-get  --yes --force-yesinstall google-chrome-stable 
sudo apt-get --yes --force-yes dist-upgrade
sudo apt-get --yes --force-yes upgrade
sudo apt-get --yes --force-yes update
sudo apt-get --yes --force-yes install gdebi
sudo apt-get --yes --force-yes install r-base r-base-dev 
sudo add-apt-repository  --yes ppa:mozillateam/firefox-next
sudo apt update && sudo apt upgrade
sudo apt-get  --yes --force-yes install vlc
sudo apt-get --yes --force-yes install conky-all
sudo apt-get --yes --force-yes install software-properties-common
sudo apt-get --yes --force-yes install apt-file
sudo apt-file --N update
sudo add-apt-repository --yes ppa:philip.scott/elementary-tweaks
sudo apt-get --yes --force-yes update
sudo apt-get --yes --force-yes install elementary-tweaks
sudo apt-get --yes --force-yes install rar unrar cabextract lzip lunzip arj unace p7zip-rar p7zip
sudo apt-get --yes --force-yes install ubuntu-restricted-extras
sudo apt  --yes --force-yes install steam
sudo apt  --yes --force-yes install openssh-server
sudo apt  --yes --force-yes install libavcodec-extra ffmpeg
sudo apt  --yes --force-yes install ardour
sudo apt-get  --yes --force-yes install libavcodec-extra
sudo apt-get  --yes --force-yes install libdvd-pkg
sudo apt-add-repository multiverse && sudo apt-get update
sudo apt-get  --yes --force-yes install libjpeg62 
sudo apt-get  --yes --force-yes install libstreamer0.10-0 
sudo apt-get  --yes --force-yes install libgstreamer-plugins-base0.10-0  
wget https://s3.amazonaws.com/rstudio-dailybuilds/rstudio-1.1.383-amd64.deb
sudo dpkg -i rstudio-1.1.383-amd64.deb
sudo apt-get  --yes --force-yes install flashplugin-installer 
sudo apt-get --yes --force-yes autoremove
# packages etc
sudo apt-get --yes --force-yes install libcurl14-gnutls-dev
sudo apt-get  --yes --force-yes install libssl-dev
#sudo apt-get  --yes --force-yes install openssl-devel
sudo apt-get  --yes --force-yes install openssl
sudo apt-get  --yes --force-yes install libssh2-1-dev 
sudo apt-get --yes --force-yes install libxml2-dev 
sudo apt-get --yes --force-yes install libmariadb-client-lgpl-dev
sudo su - -c "R -e \"install.packages('devtools', repos = 'http://cran.rstudio.com/')\""
sudo su - -c "R -e \"install.packages('tidyverse', repos = 'http://cran.rstudio.com/')\""
sudo su - -c "R -e \"install.packages('shiny', repos = 'http://cran.rstudio.com/')\""

